<?php
    class Modeldiagnosticreport extends CI_Model{
        
        function diagnosticreportlab($env){
            $query =
                    "
                        SELECT A.PASIEN_ID, EPISODE_ID, TEST_ID, CATATAN, TRANS_CO,
                                --Patient Index
                                SR01_GET_SUFFIX(A.PASIEN_ID)PATIENTNAME,
                                (SELECT INT_PASIEN_ID FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTMR,
                                (SELECT SATUSEHAT_ID  FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTID,

                                --Practitioner Index
                                (SELECT IHS_ID      FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERID,
                                (SELECT UPPER(NAMA) FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERNAME,

                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)RESOURCEID,
                                (SELECT POLI_ID     FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)POLIID,
                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='ServiceRequest' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)SERVICERQUESTID,
                                
                                (SELECT LISTAGG(RESOURCE_ID, ',')WITHIN GROUP (ORDER BY RESOURCE_ID) FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Observation' AND JENIS='12' AND LAYAN_ID IN ('CL','K','NA') AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)RESULTREF,

                            (SELECT NAMA_LAYAN1 FROM SR01_KEU_LAYAN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND LAYAN_ID=A.TEST_ID)NAMAPELAYANAN,
                            (SELECT TO_CHAR(LAST_UPDATED_DATE - INTERVAL '7' HOUR,'YYYY-MM-DD')||'T'||TO_CHAR(LAST_UPDATED_DATE - INTERVAL '7' HOUR,'HH24:MI:SS')||'+00:00' FROM SR01_WORKLIST_LAB WHERE LOKASI_ID='001' AND AKTIF='1' AND STATUS NOT IN ('2','3','9','0') AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO)TGLSELESAI
                            
                        FROM WEB_CO_LAB_DT A
                        WHERE A.SHOW_ITEM='1'
                        AND   A.TEST_ID IN ('LPK122','XELEKT000000010')
                        AND   A.EPISODE_ID NOT IN ('B124042267209','B124042253613','B124042256023','B124042268755','B124042256622','B124042257896','B124042260625','B124052273916','B124042260007')
                        AND   A.EPISODE_ID     IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE   WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                        AND   A.TEST_ID        IN (SELECT LAYAN_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='ServiceRequest' AND JENIS='10' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)
                        AND   A.TEST_ID        IN (SELECT LAYAN_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Specimen' AND JENIS='11' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)
                        AND   A.EPISODE_ID     IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Observation' AND JENIS='12' AND LAYAN_ID='CL' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                        AND   A.EPISODE_ID     IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Observation' AND JENIS='12' AND LAYAN_ID='NA' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                        AND   A.EPISODE_ID     IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Observation' AND JENIS='12' AND LAYAN_ID='K' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                        AND   A.EPISODE_ID NOT IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='DiagnosticReport' AND JENIS='13' AND ENVIRONMENT='production' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)
                        ORDER BY CREATED_DATE ASC
                        FETCH FIRST 10 ROWS ONLY
                    ";

			$recordset = $this->db->query($query);
			$recordset = $recordset->result();
			return $recordset;
        }
        
    }
?>
