<?php
    class Modelspecimen extends CI_Model{
        
        function specimentlab($env){
            $query =
                    "
                        SELECT A.PASIEN_ID, EPISODE_ID, TEST_ID, TRANS_CO, 
                                --Patient Index
                                SR01_GET_SUFFIX(A.PASIEN_ID)PATIENTNAME,
                                (SELECT INT_PASIEN_ID FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTMR,
                                (SELECT SATUSEHAT_ID  FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTID,

                                --Practitioner Index
                                (SELECT IHS_ID      FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERID,
                                (SELECT UPPER(NAMA) FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERNAME,

                                (SELECT SAMPEL_ID FROM SR01_WORKLIST_LAB WHERE LOKASI_ID='001' AND AKTIF='1' AND STATUS NOT IN ('2','3','9','0') AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO)SAMPELID,
                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)RESOURCEID,
                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='ServiceRequest' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)SERVICERQUESTID,
                                (SELECT POLI_ID     FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)POLIID,

                                TO_CHAR(A.CREATED_DATE - INTERVAL '7' HOUR,'YYYY-MM-DD')||'T'||TO_CHAR(CREATED_DATE - INTERVAL '7' HOUR,'HH24:MI:SS')||'+00:00' TGLORDER

                        FROM WEB_CO_LAB_DT A
                        WHERE A.SHOW_ITEM='1'
                        AND   A.TEST_ID IN ('LPK122','XELEKT000000010')
                        AND   A.EPISODE_ID     IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE   WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                        AND   A.TEST_ID        IN (SELECT LAYAN_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='ServiceRequest' AND JENIS='10' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)
                        AND   A.TEST_ID    NOT IN (SELECT LAYAN_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Specimen' AND JENIS='11' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.TEST_ID)
                        AND   A.TRANS_CO       IN (SELECT TRANS_CO FROM SR01_WORKLIST_LAB WHERE LOKASI_ID='001' AND AKTIF='1' AND STATUS NOT IN ('2','3','9','0') AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO)

                        ORDER BY CREATED_DATE ASC
                        FETCH FIRST 10 ROWS ONLY
                    ";

			$recordset = $this->db->query($query);
			$recordset = $recordset->result();
			return $recordset;
        }
        
    }
?>
