<?php
    class ModelProcedure extends CI_Model{
        function TindakanRJ($env){
            $query =
                    "
                        SELECT X.*,
                                (SELECT SNOMED_DISPLAY FROM SR01_SATUSEHAT_SNOMED_CT WHERE SNOMED_ID=X.SNOMEDCTID )SNOMEDDISPLAY,
                                (SELECT KODE_ICD FROM SR01_MED_ICD9_MS WHERE KODE=X.IDICDIX)CODEICDIX,
                                (SELECT LONG_DESCRIPTION FROM SR01_MED_ICD9_MS WHERE KODE=X.IDICDIX)DESCICDIX,

                                (SELECT SATUSEHAT_ID  FROM SR01_SATUSEHAT_LOCATION WHERE LOKASI_ID='001' AND AKTIF='1' AND STATUS='active' AND VALUE=X.POLIID)LOCATIONID,
                                (SELECT NAME          FROM SR01_SATUSEHAT_LOCATION WHERE LOKASI_ID='001' AND AKTIF='1' AND STATUS='active' AND VALUE=X.POLIID)LOCATIONNAME          

                        FROM(
                            SELECT A.PASIEN_ID, EPISODE_ID, LAYAN_ID, TRANS_CO,
                                    TO_CHAR(A.CREATED_DATE-INTERVAL '7' HOUR,'YYYY-MM-DD')||'T'||TO_CHAR(A.CREATED_DATE-INTERVAL '7' HOUR,'HH24:MI:SS')||'+00:00' CREATED_DATE,
                                    (SELECT NAMA_LAYAN1 FROM SR01_KEU_LAYAN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND LAYAN_ID=A.LAYAN_ID)NAMAPELAYANAN,
                                    (SELECT ICD_ID      FROM SR01_KEU_LAYAN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND LAYAN_ID=A.LAYAN_ID)IDICDIX,
                                    (SELECT SNOMED      FROM SR01_KEU_LAYAN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND LAYAN_ID=A.LAYAN_ID)SNOMEDCTID,
                                    (SELECT IHS_ID      FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND AKTIF='1' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERID,
                                    (SELECT UPPER(NAMA) FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND AKTIF='1' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERNAME,
                        
                                    SR01_GET_SUFFIX(A.PASIEN_ID)PATIENTNAME,
                                    (SELECT INT_PASIEN_ID FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTMR,
                                    (SELECT SATUSEHAT_ID  FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTID,

                                    (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)RESOURCEID,
                                    (SELECT POLI_ID     FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)POLIID
                                    
                            FROM WEB_CO_ALKES_DT A
                            WHERE A.SHOW_ITEM='1'
                            AND   A.EPISODE_ID      IN (SELECT EPISODE_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)
                            AND   A.LAYAN_ID         = (SELECT LAYAN_ID FROM SR01_KEU_LAYAN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND ICD_ID IS NOT NULL AND SNOMED IS NOT NULL AND LAYAN_ID=A.LAYAN_ID)
                            AND   A.LAYAN_ID    NOT IN (SELECT LAYAN_ID FROM SR01_SATUSEHAT_BUNDLE WHERE LOKASI_ID='001' AND AKTIF='1' AND POLI_ID IS NOT NULL AND RESOURCE_TYPE='Procedure' AND JENIS='5' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND LAYAN_ID=A.LAYAN_ID)
                        )X
                    ";

			$recordset = $this->db->query($query);
			$recordset = $recordset->result();
			return $recordset;
        }

    }
?>
