<?php
    class Modelmedicationrequest extends CI_Model{

        function medicationsingledose($env){
            $query =
                    "
                        SELECT X.*,
                               (SELECT NAME           FROM SR01_SATUSEHAT_POA_MS WHERE LOKASI_ID='001' AND KFA_ID=X.KFAID)POANAME
                        FROM(
                            SELECT A.PASIEN_ID, EPISODE_ID, TRANS_CO, OBAT_ID, CATATAN,
                                (SELECT KFA_ID FROM SR01_FRM_OBAT_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND OBAT_ID=A.OBAT_ID)KFAID,

                                SR01_GET_SUFFIX(A.PASIEN_ID)PATIENTNAME,
                                (SELECT INT_PASIEN_ID FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTMR,
                                (SELECT SATUSEHAT_ID  FROM SR01_GEN_PASIEN_MS WHERE LOKASI_ID='001' AND AKTIF='1' AND PASIEN_ID=A.PASIEN_ID)PATIENTID,

                                (SELECT IHS_ID      FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND AKTIF='1' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERID,
                                (SELECT UPPER(NAMA) FROM SR01_GEN_USER_DATA WHERE LOKASI_ID='001' AND AKTIF='1' AND DOKTER_ID=A.CREATED_BY)PRACTITIONERNAME,

                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_TRANSAKSI WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)RESOURCEID,
                                (SELECT RESOURCE_ID FROM SR01_SATUSEHAT_TRANSAKSI WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Medication' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO AND OBAT_ID=A.OBAT_ID)MEDICATIONID,
                                (SELECT POLI_ID     FROM SR01_SATUSEHAT_TRANSAKSI WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)POLI_ID,
                                (SELECT DOKTER_ID   FROM SR01_SATUSEHAT_TRANSAKSI WHERE LOKASI_ID='001' AND AKTIF='1' AND RESOURCE_TYPE='Encounter' AND ENVIRONMENT='".$env."' AND PASIEN_ID=A.PASIEN_ID AND EPISODE_ID=A.EPISODE_ID)DOKTER_ID,
                                TO_CHAR(CREATED_DATE - INTERVAL '7' HOUR,'YYYY-MM-DD')||'T'||TO_CHAR(CREATED_DATE - INTERVAL '7' HOUR,'HH24:MI:SS')||'+00:00' CREATEDDATE

                            FROM WEB_CO_RESEP_DT A
                            WHERE A.SHOW_ITEM='1'
                            AND   A.TYPE='00'
                            AND   EXISTS (SELECT 1 FROM SR01_FRM_OBAT_MS WHERE OBAT_ID=A.OBAT_ID AND KFA_ID IS NOT NULL)
                            AND   EXISTS (SELECT 1 FROM SR01_SATUSEHAT_TRANSAKSI T WHERE T.LOKASI_ID='001' AND T.AKTIF='1' AND T.RESOURCE_TYPE='Encounter' AND T.JENIS='1' AND T.ENVIRONMENT='".$env."' AND T.PASIEN_ID=A.PASIEN_ID AND T.EPISODE_ID=A.EPISODE_ID)
                            AND   EXISTS (SELECT 1 FROM SR01_SATUSEHAT_TRANSAKSI T WHERE T.LOKASI_ID='001' AND T.AKTIF='1' AND T.RESOURCE_TYPE='Medication' AND T.JENIS='1' AND T.ENVIRONMENT='".$env."' AND T.PASIEN_ID=A.PASIEN_ID AND T.EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO AND OBAT_ID=A.OBAT_ID)
                            AND   NOT EXISTS (SELECT 1 FROM SR01_SATUSEHAT_TRANSAKSI T WHERE T.LOKASI_ID='001' AND T.AKTIF='1' AND T.RESOURCE_TYPE='MedicationRequest' AND T.JENIS='1' AND T.ENVIRONMENT='".$env."' AND T.PASIEN_ID=A.PASIEN_ID AND T.EPISODE_ID=A.EPISODE_ID AND TRANS_CO=A.TRANS_CO AND OBAT_ID=A.OBAT_ID)
                            FETCH FIRST 10 ROWS ONLY
                        )X
                    ";

			$recordset = $this->db->query($query);
			$recordset = $recordset->result();
			return $recordset;
        }

    }
?>


